python constituency_parsing/error_analysis.py --gold_file gold_standard/gum_fiction_corpus.txt --test_file stanza_constituency_parses/gum_fiction_corpus.txt --output_file results/constituency/stanza_on_gum_fiction_corpus_errors.csv --confusion_matrix results/constituency/stanza_on_gum_fiction_corpus_confusion_matrix.csv 
python constituency_parsing/error_analysis.py --gold_file gold_standard/gum_fiction_corpus.txt --test_file benepar_constituency_parses/gum_fiction_corpus.txt --output_file results/constituency/berkeley_on_gum_fiction_corpus_errors.csv  --confusion_matrix results/constituency/berkeley_on_gum_fiction_corpus_confusion_matrix.csv 

python constituency_parsing/error_analysis.py --gold_file gold_standard/gold_standard_2024-2025.txt --test_file stanza_constituency_parses/sentences_2024-2025.txt --output_file results/constituency/stanza_on_gold_sentences.csv  --confusion_matrix results/constituency/stanza_on_gold_sentences_confusion_matrix.csv 
python constituency_parsing/error_analysis.py --gold_file gold_standard/gold_standard_2024-2025.txt --test_file benepar_constituency_parses/sentences_2024-2025.txt --output_file results/constituency/berkeley_on_gold_sentences.csv  --confusion_matrix results/constituency/berkeley_on_gold_sentences_confusion_matrix.csv 

python constituency_parsing/error_analysis.py --gold_file gold_standard/gum_news_corpus.txt --test_file benepar_constituency_parses/gum_news_corpus.txt --output_file results/constituency/berkeley_on_gum_news_corpus_errors.csv  --confusion_matrix results/constituency/stanza_on_gum_news_corpus_confusion_matrix.csv 
python constituency_parsing/error_analysis.py --gold_file gold_standard/gum_news_corpus.txt --test_file stanza_constituency_parses/gum_news_corpus.txt --output_file results/constituency/stanza_on_gum_news_corpus_errors.csv  --confusion_matrix results/constituency/berkeley_on_gum_news_corpus_confusion_matrix.csv

python constituency_parsing/error_analysis.py --gold_file gold_standard/gold_standard_2024-2025_adversarial.txt --test_file benepar_constituency_parses/sentences_2024-2025_adversarial.txt --output_file results/constituency/berkeley_on_adversarial_errors.csv  --confusion_matrix results/constituency/berkeley_on_adversarial_confusion_matrix.csv
python constituency_parsing/error_analysis.py --gold_file gold_standard/gold_standard_2024-2025_adversarial.txt --test_file stanza_constituency_parses/sentences_2024-2025_adversarial.txt --output_file results/constituency/stanza_on_adversarial_errors.csv  --confusion_matrix results/constituency/stanza_on_adversarial_confusion_matrix.csv  